import LoaderWrapper from '@/components/pages/PageLoader/LoaderWrapper'
import { Metadata } from 'next'
import './globals.css'
import Header from '@/components/shares/templates/HeaderComponents/Header'
import Footer from '@/components/shares/templates/FooterComponents/Footer'

export const metadata: Metadata = {
  title: 'Last Produce株式会社（ラストプロデュース株式会社）| 東京都・神奈川県の葬儀法要',
  description: 'Generated by create next appラストプロデュースは関東圏で活動する葬儀社です。それぞれの「ありがとう」を形にして、故人様の華々しい最後を飾るお手伝いをさせていただきます。お問い合わせは24時間365日受け付けております。',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className='bg-main-bg'>
        <LoaderWrapper>
          <Header />

          {children}

          <Footer />
        </LoaderWrapper>
      </body>
    </html>
  )
}
